language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python render.py
- chmod 600 .travis/deploy_key.pem
- ssh-add .travis/deploy_key.pem
- git remote add deploy git@github.com:omniavinco/translate_xkcd.git
- git fetch deploy
- git checkout -b gh-pages deploy/gh-pages
- find . -maxdepth 1 -name "*.html" -exec git rm --ignore-unmatch -q {} \;
- git rm --ignore-unmatch -q res
- git checkout master -- res
- mv out/*.html .
- git add res *.html
- git commit -m"Static page generated"
- git push deploy
before_install:
- openssl aes-256-cbc -K $encrypted_bd2a943abb02_key -iv $encrypted_bd2a943abb02_iv
  -in deploy_key.pem.enc -out .travis/deploy_key.pem -d
