language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- python render.py
- chmod 600 .travis/deploy_key.pem
- eval `ssh-agent -s`
- ssh-add .travis/deploy_key.pem
- git config user.email "omniavinco@gmail.com"
- git config user.name "Gyusun Yeom"
- git config push.default simple
- git remote add deploy git@github.com:Perlmint/translate_xkcd.git
- git fetch deploy
- git checkout -b gh-pages deploy/gh-pages
- find . -maxdepth 1 -name "*.html" -exec git rm --ignore-unmatch -q {} \;
- git rm --ignore-unmatch -q -r res
- git checkout master -- res
- mv out/*.html .
- git add res *.html
- find . -name index.html -exec git add {} \;
- if [ `git diff --cached | wc -l` -ne 0 ] ; then  git commit -m"Static page generated" && git push deploy; fi
before_install:
- mkdir -p .travis
- openssl aes-256-cbc -K $encrypted_bd2a943abb02_key -iv $encrypted_bd2a943abb02_iv
  -in deploy_key.pem.enc -out .travis/deploy_key.pem -d
